### ISSUE TITLE
Error in footer.php

### ISSUE THREAD

**Issue by ralondo** [elmastudio/dorayaki#1]
I am getting this error with the latest release:

PHP Parse error:  syntax error, unexpected 'endif' (T_ENDIF), expecting end of file in /xxx/wp-content/themes/dorayaki/footer.php on line 55

When I remove the "`<?php endif; ?>`", then everything works fine.

**Comment by fol9000** [comment]
Same here. The error didn't show up directly but a plugin didn't work as expected. As long as this bug is not fixed and sth does not work as expected: remove the line first and see what happens...

**Comment by 2ndkauboy** [comment]
I think you are right! This seems to be some left-over code when the Twitter and Google+ JavaScript code was removed from the `footer.php` file. Good catch!
